"""Obsidian vault writer — materializes each reflection into the world model.

Two surfaces:

1. **Daily notes** at ``journal/YYYY-MM-DD.md`` — one file per calendar day.
   Each reflection is rendered as a self-contained, marker-delimited block.
   Re-running for the same reflection replaces its block in place, so the
   writer is fully idempotent: the backfill and the live pipeline can both
   call ``write_reflection`` safely without dup'ing content.

2. **Entity files** at ``entities/{people,projects,concepts,decisions}/<slug>.md``
   — one per distinct entity. Frontmatter is regenerated from SQLite on each
   touch (mention count, first/last seen), and the timeline section is
   rebuilt from the entity_mentions table so it always reflects ground truth.

The vault is the user's actual Obsidian vault (config/pudge-bot/). It is its
own git repo; failures here never break the ingest pipeline (callers wrap in
try/except). Manual edits coexist with auto-writes via marker fences —
anything outside the AUTO blocks is preserved verbatim.
"""
from __future__ import annotations

import logging
import re
from datetime import datetime
from pathlib import Path

import db
from config import JOURNAL_DIR, ENTITIES_DIR

log = logging.getLogger("orb.vault")

# Markers used to fence auto-managed regions. Anything between BEGIN/END
# for a given key is owned by the writer; everything outside is the user's.
_BEGIN = "<!-- orb:auto BEGIN {key} -->"
_END = "<!-- orb:auto END {key} -->"

_KIND_DIRS = {
    "person":   "people",
    "project":  "projects",
    "concept":  "concepts",
    "decision": "decisions",
}


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def write_reflection(
    *,
    rec_id: int,
    recorded_at: datetime,
    source: str,
    transcript: str,
    parsed: dict,
    entities: list[dict],
    acoustic: dict | None = None,
    note_title: str | None = None,
) -> None:
    """Materialize one reflection: daily-note block + touch each entity file."""
    _ensure_dirs()
    _upsert_daily_block(
        rec_id=rec_id,
        recorded_at=recorded_at,
        source=source,
        transcript=transcript,
        parsed=parsed,
        entities=entities,
        acoustic=acoustic,
        note_title=note_title,
    )
    seen_files: set[Path] = set()
    for ent in entities or []:
        path = _entity_path(ent["kind"], ent["slug"])
        if path in seen_files:
            continue
        seen_files.add(path)
        _rewrite_entity_file(path, ent["kind"], ent["slug"], ent["name"])


def rewrite_entity(kind: str, slug: str, name: str | None = None) -> Path:
    """Force-regenerate one entity file from the current DB state."""
    _ensure_dirs()
    path = _entity_path(kind, slug)
    display = name
    if display is None:
        rows = db.entity_timeline(kind, slug, limit=1)
        display = rows[0]["name"] if rows else slug
    _rewrite_entity_file(path, kind, slug, display)
    return path


def daily_note_path(day: datetime | str) -> Path:
    if isinstance(day, datetime):
        day = day.date().isoformat()
    return JOURNAL_DIR / f"{day}.md"


# ---------------------------------------------------------------------------
# Daily notes
# ---------------------------------------------------------------------------

def _upsert_daily_block(
    *,
    rec_id: int,
    recorded_at: datetime,
    source: str,
    transcript: str,
    parsed: dict,
    entities: list[dict],
    acoustic: dict | None,
    note_title: str | None,
) -> None:
    path = daily_note_path(recorded_at)
    key = f"rec-{rec_id}"
    block = _render_reflection_block(
        rec_id=rec_id,
        recorded_at=recorded_at,
        source=source,
        transcript=transcript,
        parsed=parsed,
        entities=entities,
        acoustic=acoustic,
        note_title=note_title,
    )
    body = path.read_text() if path.exists() else _new_daily_skeleton(recorded_at)
    body = _upsert_marker_block(body, key, block)
    # Keep blocks ordered by recorded_at — easier to scan, makes diffs sane.
    body = _sort_daily_blocks(body)
    _atomic_write(path, body)


def _new_daily_skeleton(recorded_at: datetime) -> str:
    day = recorded_at.date().isoformat()
    weekday = recorded_at.strftime("%A")
    return (
        f"---\ntype: daily\ndate: {day}\n---\n\n"
        f"# {day} · {weekday}\n\n"
        f"> *Generated by the orb. Reflection blocks are marker-fenced and overwritten on re-ingest; everything outside the fences is yours.*\n\n"
    )


def _render_reflection_block(
    *,
    rec_id: int,
    recorded_at: datetime,
    source: str,
    transcript: str,
    parsed: dict,
    entities: list[dict],
    acoustic: dict | None,
    note_title: str | None,
) -> str:
    time_str = recorded_at.strftime("%H:%M")
    mood = (parsed.get("mood") or "—").strip()
    summary = (parsed.get("summary") or "").strip()
    pattern = (parsed.get("pattern") or "").strip()
    question = (parsed.get("question") or "").strip()
    themes = _split_csv(parsed.get("themes"))
    inconsistencies = [x for x in (parsed.get("inconsistencies") or []) if isinstance(x, str) and x.strip()]
    proposals = [p for p in (parsed.get("proposals") or []) if isinstance(p, dict)]

    src_icon = "📓" if source == "note" else "🎙"
    src_label = "note" if source == "note" else "voice"
    header = f"## {time_str} · {src_icon} {src_label} · {mood}"
    if note_title and source == "note":
        header += f" · *{_escape(note_title)}*"

    lines: list[str] = [header, ""]

    if summary:
        lines.append(summary)
        lines.append("")

    if themes:
        tag_line = " ".join(f"#theme/{t}" for t in themes)
        lines.append(tag_line)
        lines.append("")

    if entities:
        lines.append("**entities:** " + ", ".join(
            f"[[{_entity_link_target(e['kind'], e['slug'])}|{e['name']}]]"
            for e in entities
        ))
        lines.append("")

    if pattern:
        lines.append(f"**pattern:** {pattern}")
        lines.append("")

    if question:
        lines.append(f"**q:** {question}")
        lines.append("")

    if inconsistencies:
        lines.append("**inconsistencies:**")
        for x in inconsistencies:
            lines.append(f"- {x.strip()}")
        lines.append("")

    if proposals:
        lines.append("**proposals:**")
        for p in proposals:
            file = (p.get("file") or "?").strip()
            section = (p.get("section") or "").strip()
            text = (p.get("proposal") or "").strip()
            section_str = f" / {section}" if section else ""
            lines.append(f"- `{file}{section_str}` — {text}")
        lines.append("")

    if acoustic:
        wpm = acoustic.get("speaking_rate_wpm")
        pause = acoustic.get("pause_ratio")
        dur = acoustic.get("duration_sec")
        parts = []
        if dur is not None:
            parts.append(f"{int(dur)}s")
        if wpm is not None:
            parts.append(f"{wpm:.0f} wpm")
        if pause is not None:
            parts.append(f"{pause:.0%} pauses")
        if parts:
            lines.append("*" + " · ".join(parts) + "*")
            lines.append("")

    if transcript and transcript.strip():
        lines.append("> [!quote]- transcript")
        for tline in transcript.strip().splitlines() or [""]:
            lines.append(f"> {tline}" if tline else ">")
        lines.append("")

    # Obsidian block-id anchor — lets entity timelines link back here.
    lines.append(f"^rec-{rec_id}")
    lines.append("")

    return "\n".join(lines).rstrip() + "\n"


# ---------------------------------------------------------------------------
# Entity files
# ---------------------------------------------------------------------------

def _entity_path(kind: str, slug: str) -> Path:
    sub = _KIND_DIRS.get(kind, "misc")
    return ENTITIES_DIR / sub / f"{slug}.md"


def _entity_link_target(kind: str, slug: str) -> str:
    sub = _KIND_DIRS.get(kind, "misc")
    return f"entities/{sub}/{slug}"


def _rewrite_entity_file(path: Path, kind: str, slug: str, display_name: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    timeline = db.entity_timeline(kind, slug, limit=500)
    if not timeline:
        # Edge case — caller hands us an entity that has no mentions. Skip.
        return

    first = timeline[0]["recorded_at"][:10]
    last = timeline[-1]["recorded_at"][:10]
    mentions = len(timeline)
    aliases = sorted({row["name"] for row in timeline if row["name"]})

    front_lines = [
        "---",
        f"type: entity/{kind}",
        f"slug: {slug}",
        f"name: {display_name}",
        f"first_seen: {first}",
        f"last_seen: {last}",
        f"mentions: {mentions}",
    ]
    if len(aliases) > 1:
        front_lines.append("aliases:")
        for a in aliases:
            front_lines.append(f"  - {a}")
    front_lines.append("---")
    frontmatter = "\n".join(front_lines)

    header = f"# {display_name}\n\n*{kind} · {mentions} mention{'s' if mentions != 1 else ''} · first {first} · last {last}*\n"

    timeline_lines = ["## Timeline", ""]
    for row in timeline:
        date = row["recorded_at"][:10]
        rec_id = row["recording_id"]
        mood = row["mood"] or ""
        ctx = (row["context"] or "").replace("\n", " ").strip()
        if not ctx and row["summary"]:
            ctx = _first_sentence(row["summary"])
        mood_str = f" · {mood}" if mood else ""
        link = f"[[journal/{date}#^rec-{rec_id}|{date}]]"
        # Obsidian block-id link works once the daily note carries a ^rec-N anchor.
        # We add the anchor in the rendered reflection block (see TIMELINE_ANCHOR).
        timeline_lines.append(f"- {link}{mood_str} — {ctx}" if ctx else f"- {link}{mood_str}")

    # User-owned regions live between the fences; we preserve them across rewrites.
    existing = path.read_text() if path.exists() else ""
    notes_region = _extract_marker_block(existing, "user-notes") or (
        f"{_BEGIN.format(key='user-notes')}\n"
        f"<!-- your own notes about {display_name} go here; the orb won't touch this region -->\n\n"
        f"{_END.format(key='user-notes')}"
    )

    body = (
        f"{frontmatter}\n\n"
        f"{header}\n"
        f"{_BEGIN.format(key='timeline')}\n"
        + "\n".join(timeline_lines) + "\n"
        f"{_END.format(key='timeline')}\n\n"
        f"## Notes\n\n"
        f"{notes_region}\n"
    )
    _atomic_write(path, body)


# ---------------------------------------------------------------------------
# Marker-block helpers
# ---------------------------------------------------------------------------

def _marker_re(key: str) -> re.Pattern[str]:
    begin = re.escape(_BEGIN.format(key=key))
    end = re.escape(_END.format(key=key))
    return re.compile(rf"{begin}.*?{end}\n?", re.DOTALL)


def _upsert_marker_block(body: str, key: str, content: str) -> str:
    block = f"{_BEGIN.format(key=key)}\n{content.rstrip()}\n{_END.format(key=key)}\n"
    pattern = _marker_re(key)
    if pattern.search(body):
        return pattern.sub(block, body)
    # Append. Ensure exactly one blank line of separation.
    sep = "" if body.endswith("\n\n") else ("\n" if body.endswith("\n") else "\n\n")
    return body + sep + block


def _extract_marker_block(body: str, key: str) -> str | None:
    m = _marker_re(key).search(body)
    return m.group(0).rstrip("\n") if m else None


def _sort_daily_blocks(body: str) -> str:
    """Sort all `rec-*` marker blocks by their first heading time prefix.

    Daily notes accumulate one block per reflection; the timestamp is the
    first `## HH:MM` line inside the block. Keeping them in chronological
    order makes the file readable without forcing the caller to know about
    sibling reflections.
    """
    re_rec = re.compile(
        rf"{re.escape('<!-- orb:auto BEGIN ')}rec-(\d+){re.escape(' -->')}"
        r".*?"
        rf"{re.escape('<!-- orb:auto END ')}rec-\1{re.escape(' -->')}\n?",
        re.DOTALL,
    )
    blocks = list(re_rec.finditer(body))
    if len(blocks) < 2:
        return body

    def time_key(text: str) -> str:
        m = re.search(r"^## (\d{2}:\d{2})", text, re.MULTILINE)
        return m.group(1) if m else "99:99"

    spans = [(m.start(), m.end(), m.group(0)) for m in blocks]
    sorted_blocks = sorted(spans, key=lambda s: time_key(s[2]))
    # Re-emit: keep the pre/post text, replace block region in original order
    # with the time-sorted versions.
    out = body[: spans[0][0]]
    out += "\n".join(b[2].rstrip("\n") for b in sorted_blocks) + "\n"
    out += body[spans[-1][1] :]
    return out


# ---------------------------------------------------------------------------
# Misc helpers
# ---------------------------------------------------------------------------

def _split_csv(value) -> list[str]:
    if not value:
        return []
    return [t.strip().lower() for t in str(value).split(",") if t.strip()]


def _first_sentence(text: str, hard_cap: int = 140) -> str:
    text = (text or "").replace("\n", " ").strip()
    if not text:
        return ""
    for sep in (". ", "? ", "! "):
        idx = text.find(sep)
        if 0 < idx < hard_cap:
            return text[: idx + 1].strip()
    if len(text) <= hard_cap:
        return text
    return text[:hard_cap].rstrip() + "…"


def _escape(s: str) -> str:
    return s.replace("\n", " ").strip()


def _ensure_dirs() -> None:
    JOURNAL_DIR.mkdir(parents=True, exist_ok=True)
    ENTITIES_DIR.mkdir(parents=True, exist_ok=True)
    for sub in _KIND_DIRS.values():
        (ENTITIES_DIR / sub).mkdir(parents=True, exist_ok=True)


def _atomic_write(path: Path, body: str) -> None:
    """Write through a tempfile + rename so an interrupted run never leaves a half-file."""
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(body)
    tmp.replace(path)
